# Generated by Django 6.0.6 on 2026-06-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_orderitem_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profile'},
        ),
    ]
